/* SESSION */
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR'

export const REQUEST_LOGGED_IN_USER = 'REQUEST_LOGGED_IN_USER'
export const GET_LOGGED_IN_USER_SUCCESS = 'GET_LOGGED_IN_USER_SUCCESS'
export const GET_LOGGED_IN_USER_ERROR = 'GET_LOGGED_IN_USER_ERROR'

/* CHAT ROOM */
export const REQUEST_LOAD_CHAT_MESSAGES = 'REQUEST_LOAD_CHAT_MESSAGES'
export const LOAD_CHAT_MESSAGES_SUCCESS = 'LOAD_CHAT_MESSAGES_SUCCESS'
export const LOAD_CHAT_MESSAGES_ERROR = 'LOAD_CHAT_MESSAGES_ERROR'

export const REQUEST_ADD_CHAT_MESSAGE = 'REQUEST_ADD_CHAT_MESSAGE'
export const ADD_CHAT_MESSAGE_SUCCESS = 'POST_CHAT_MESSAGE_SUCCESS'
export const ADD_CHAT_MESSAGE_ERROR = 'POST_CHAT_MESSAGE_ERROR'

/* COUNTER */
export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED'
export const INCREMENT = 'INCREMENT'
export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED'
export const DECREMENT = 'DECREMENT'
