/* SESSION */
export const REQUEST_LOGIN = 'REQUEST_LOGIN'

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'
export const LOG_OUT_ERROR = 'LOG_OUT_ERROR'
export const REQUEST_LOGGED_IN_USER = 'REQUEST_LOGGED_IN_USER'

export const GET_LOGGED_IN_USER_SUCCESS = 'GET_LOGGED_IN_USER_SUCCESS'
export const GET_LOGGED_IN_USER_ERROR = 'GET_LOGGED_IN_USER_ERROR'

/* COUNTER */
export const INCREMENT_REQUESTED = 'INCREMENT_REQUESTED'
export const INCREMENT = 'INCREMENT'
export const DECREMENT_REQUESTED = 'DECREMENT_REQUESTED'
export const DECREMENT = 'DECREMENT'
